### ISSUE TITLE
Consider linting with flake8

### ISSUE THREAD

**Issue by Carreau** [zmoitier/claudius#5]
```
$ flake8 . --ignore E501,F811,E731,E741,W503,E203,F401
./claudius/normL2.py:8:13: F821 undefined name 'sol'
./claudius/normL2.py:15:9: F841 local variable 'δ' is assigned to but never used
./claudius/normL2.py:15:14: F821 undefined name 'sol'
./claudius/plot/anim_field.py:58:5: F841 local variable 'anim' is assigned to but never used
```

That catches many mistakes; I've ignore in the above the most commons errors, like spaces, and unused imports.

**Comment by zmoitier** [comment]
I do use pylint through my editor and it does complain a lot about my naming style. I am trying to be careful for function variables but for internal variable my mathematical bias toward sort notations take is upper hand.

**Comment by Carreau** [comment]
Ok, one of the other; you can also add them in CI if you wish; but as long as you know about them. 
Feel free to close.
